In [1]:
#NUMPY is use for numerical python
!pip install numpy
#pip - python installing packages

In [3]:
import numpy

In [4]:
import numpy as np

In [5]:
# as - alias

In [6]:
# array - 1D array 2D array 3D array

In [7]:
arr = np.array([40,50,60,70])

In [8]:
arr

array([40, 50, 60, 70])

In [9]:
arr.ndim

1

In [11]:

arr2 = np.array([[10,20,30], [40,50,60]])

In [12]:
arr2

array([[10, 20, 30],
       [40, 50, 60]])

In [13]:
arr2.ndim

2

In [14]:
arr2.shape  #check the shape

(2, 3)

In [15]:
arr2.size

6

In [16]:
arr2.dtype

dtype('int64')

In [17]:
arr2

array([[10, 20, 30],
       [40, 50, 60]])

In [18]:
arr2.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [19]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [20]:
arr.shape

(3, 3)

In [21]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.ndim

2

In [26]:
arr[2,0]

np.int64(7)

In [24]:
arr[1,2]

np.int64(6)

In [25]:
arr[2,2]

np.int64(9)

In [28]:
arr1 = np.array([[1,2,3], [4,5,6]])

In [29]:
arr1.shape

(2, 3)

In [30]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [34]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [35]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.full((3,3), 8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [38]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
arr = np.array([11,24,35,44,74,25])

In [40]:
arr1 = np.array([1,2,2,4,5,6])

In [41]:
arr + arr1

array([12, 26, 37, 48, 79, 31])

In [42]:
np.add(arr, arr1)

array([12, 26, 37, 48, 79, 31])

In [43]:
np.sum(arr)

np.int64(213)

In [44]:
np.mean(arr)

np.float64(35.5)

In [45]:
np.median(arr)

np.float64(30.0)

In [46]:
np.std(arr)

np.float64(19.98958061924595)

In [47]:
np.var(arr)

np.float64(399.5833333333333)

In [48]:
np.max(arr)

np.int64(74)

In [49]:
np.min(arr)

np.int64(11)

In [50]:
np.percentile(arr, 75)

np.float64(41.75)

In [52]:
np.quantile(arr, 0.75)

np.float64(41.75)

In [53]:
np.corrcoef(arr, arr1)

array([[1.        , 0.53415237],
       [0.53415237, 1.        ]])

In [54]:
np.cov(arr, arr1)

array([[479.5       ,  23.        ],
       [ 23.        ,   3.86666667]])

In [55]:
np.sort(arr)

array([11, 24, 25, 35, 44, 74])

In [56]:
np.unique(arr)

array([11, 24, 25, 35, 44, 74])

In [60]:
# random

In [65]:
np.random.rand(2,3)
#.rand range is 0 to 1

array([[0.55060495, 0.00732517, 0.07581114],
       [0.10022042, 0.29489028, 0.67845747]])

In [68]:
np.random.randn(2,3)
#n is for normal distributed data mean = 0

array([[-0.6434236 , -0.76833791,  0.80388384],
       [ 0.64853031, -0.58904165, -0.49231473]])

In [71]:
np.random.randint(1,20,5)

array([15,  9, 14, 16,  8])

In [76]:
np.random.randint(1,6,1)

array([4])

In [80]:
np.random.random((2,2))

array([[0.45669826, 0.03835777],
       [0.02499723, 0.4048821 ]])

In [81]:
arr

array([11, 24, 35, 44, 74, 25])

In [82]:
np.random.shuffle(arr)

In [83]:
arr

array([25, 11, 74, 24, 35, 44])